#!/bin/bash

# Se il file della tabella dei colori esiste,
if [[ -f "${coltable}" ]]; then
    # includilo
    # shellcheck source="./advanced/Scripts/COL_TABLE"
    source "${coltable}"
# Altrimenti,
else
    # Imposta questi valori in modo che lo script possa ancora essere eseguito a colori
    COL_NC='\033[0m'    # No Color
    COL_GREEN='\033[0;32m' # Verde
    COL_BLUE='\033[0;34m'  # Blu
    COL_RED='\033[0;31m'   # Rosso
    TICK="[${COL_GREEN}✓${COL_NC}]"
    CROSS="[${COL_RED}✗${COL_NC}]"
    INFO="[${COL_BLUE}i${COL_NC}]"
    OVER="\\r\\033[K"
fi


echo -e "${COL_BLUE}"
echo "  .                                                ***                                               "
echo "    *************************:                     *******           **********************          "
echo "    **************************                   ***********         **********************          "
echo "    ***************************                :**********           **********************          "
echo "    ***************************+              **********             **********************          "
echo "                  :**********+              **********.              *******                         "
echo "                .**********+              **********+                *******                         "
echo "              .**********+              ***********                  *******                         "
echo "            .**********+              =**********                    *******                         "
echo "          .***********              .**********   *****              *******        ****-            "
echo "           **************          **********.    ********+          *******        ********         "
echo "           .***************       *********=      ***********        *******        **********.      "
echo "            +****************       ******        ************       *******        ************     "
echo "                   .**********        **             **********:                      .**********    "
echo "                      *********                         ********                         ********* . "
echo "                       ********                          ********                         =*******   "
echo "                        *******                          :*******                          *******+  "
echo "  *******               *******.   ********              .*******    *******               ********  "
echo "  *******+             .*******    -*******              ********   .********              *******.  "
echo "  ********=           .********     ********            ********:    =********            ********   "
echo "   *********.        *********      .*********        **********      *********=        *********    "
echo "    *************************        .*************************        *************************     "
echo "     ***********************           **********************.          :**********************      "
echo "       *******************               ******************:              -******************        "
echo "          +************                     ************-                    -************           "
echo "              .                                                                                      " 
echo -e "${COL_WHITE}"
echo ""
echo "              ______ _                 _                                  _____ _______ "
echo "             |  ____| |               | |                                |_   _|__   __|"
echo "             | |__  | | _____   ____ _| |_ ___   _   _  ___  _   _ _ __    | |    | |   "
echo "             |  __| | |/ _ \ \ / / _` | __/ _ \ | | | |/ _ \| | | | .__|   | |    | |   "
echo "             | |____| |  __/\ V / (_| | | | __/ | |_| | (_) | |_| | |     _| |_   | |   "
echo "             |______|_|\___| \_/ \__,_|\__\___|  \__, |\___/ \__,_|_|    |_____|  |_|   "
echo "                                                  __/ |                                 "
echo "                                                 |___/                                  "
echo ""
echo ""
echo -e "${COL_NC}"

# Verifica che lo script sia eseguito come root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Questo script deve essere eseguito come root."
  exit 1
fi

echo "✅ Esecuzione come root confermata."




# Chiede la password del database in modo interattivo
echo -n "🔐 Inserisci la password dell'utente ksc: "
read -s KSC_PASSWORD
echo ""
# Chiede la password del database in modo interattivo
echo -n "🔐 Inserisci la password del database PostgreSQL: "
read -s DB_PASSWORD
echo ""








echo -e "${COL_GREEN} ┌─────────────────────────────────┐"
echo -e "${COL_GREEN} │ Aggiornamento Sistema Operativo │"
echo -e "${COL_GREEN} └─────────────────────────────────┘"

	sudo apt update && sudo apt upgrade

echo -e "${COL_GREEN} ┌──────────────────────────┐"
echo -e "${COL_GREEN} │ Installazione Postgresql │"
echo -e "${COL_GREEN} └──────────────────────────┘"

	apt install postgresql -y

echo -e "${COL_GREEN} ┌──────────────────────────────────────────┐"
echo -e "${COL_GREEN} │ Ottimizzazione configurazione Postgresql │"
echo -e "${COL_GREEN} └──────────────────────────────────────────┘"



echo -e "${COL_GREEN} ┌──────────────────────┐"
echo -e "${COL_GREEN} │ Creazione Utente ksc │"
echo -e "${COL_GREEN} └──────────────────────┘"

	sudo useradd -m -s /bin/bash "ksc"
	echo "ksc:$KSC_PASSWORD" | sudo chpasswd
	sudo usermod -g kladmins ksc
	
	#sudo adduser ksc
	#sudo groupadd kladmins
	#sudo usermod -g kladmins ksc

echo -e "${COL_GREEN} ┌─────────────────────────────┐"
echo -e "${COL_GREEN} │ Creazione Utente Postgresql │"
echo -e "${COL_GREEN} └─────────────────────────────┘"

	sudo -u postgres psql -c "CREATE USER ksc WITH PASSWORD '$DB' SUPERUSER;"

echo -e "${COL_GREEN} ┌──────────────────┐"
echo -e "${COL_GREEN} │ Creazione DB KAV │"
echo -e "${COL_GREEN} └──────────────────┘"

	sudo -u ksc createdb KAV

echo -e "${COL_GREEN} ┌──────────────┐"
echo -e "${COL_GREEN} │ Download KSC │"
echo -e "${COL_GREEN} └──────────────┘"

	wget -P /tmp/ https://products.s.kaspersky-labs.com/administrationkit/ksc10/15.4.0.8873/english-24733053-en/3939393939367c44454c7c31/ksc64_15.4.0-8873_amd64.deb

echo -e "${COL_GREEN} ┌───────────────────┐"
echo -e "${COL_GREEN} │ Installazione KSC │"
echo -e "${COL_GREEN} └───────────────────┘"

	sudo apt install /tmp/ksc64_15.4.0-8873_amd64.deb

echo -e "${COL_GREEN} ┌────────────────────┐"
echo -e "${COL_GREEN} │ Configurazione KSC │"
echo -e "${COL_GREEN} └────────────────────┘"

	sudo /opt/kaspersky/ksc64/lib/bin/setup/postinstall.pl
	
	
	
	
	# Define the file path
FILE_PATH="/etc/ksc-web-console-setup.json"

# Use a here document to create the file with the specified content
cat << EOF | sudo tee "$FILE_PATH" > /dev/null
{
 "address": "127.0.0.1",
 "port": 8080,
 "trusted": "127.0.0.1|13299|/var/opt/kaspersky/klnagent_srv/1093/cert/klserver.cer|KSC Server",
 "acceptEula": true
}
EOF

echo "File $FILE_PATH creato con successo."

wget -P /tmp/ https://products.s.kaspersky-labs.com/administrationkit/ksc10/15.4.0.8952/english-25132578-en/313031343938397c44454c7c31/ksc-web-console-15.4.1021.x86_64.deb

sudo dpkg -i /tmp/ksc-web-console-15.4.1021.x86_64.deb

